-- MySQL Script generated by MySQL Workbench
-- 01/26/16 14:36:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group` (
  `group_id` INT NOT NULL,
  `inheritance_id` INT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `groupcol` VARCHAR(45) NULL,
  PRIMARY KEY (`group_id`),
  UNIQUE INDEX `group_title` (`title` ASC),
  INDEX `inheritance_id` (`inheritance_id` ASC),
  CONSTRAINT `inheritance_id`
    FOREIGN KEY (`inheritance_id`)
    REFERENCES `group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account` (
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(61) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `ssn` VARCHAR(45) NOT NULL,
  `accountcol` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `ssn` (`ssn` ASC),
  UNIQUE INDEX `username` (`username` ASC),
  INDEX `group_id` (`group_id` ASC),
  CONSTRAINT `group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profile` (
  `profile_id` INT NOT NULL,
  `user_id` INT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `avatar_url` VARCHAR(45) NULL,
  `show_city` TINYINT(1) NOT NULL DEFAULT 1,
  `show_address` TINYINT(1) NOT NULL DEFAULT 1,
  `show_age` TINYINT(1) NOT NULL DEFAULT 1,
  `show_avatar` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`profile_id`),
  UNIQUE INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `account` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profile_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profile_rating` (
  `ratings_id` INT NOT NULL,
  `profile_id` INT NOT NULL,
  `author_id` INT NULL,
  `rating` INT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`ratings_id`),
  INDEX `profile_id` (`profile_id` ASC),
  INDEX `author_id` (`author_id` ASC),
  CONSTRAINT `profile_id`
    FOREIGN KEY (`profile_id`)
    REFERENCES `profile` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `profile` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profile_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profile_contact` (
  `contact_id` INT NOT NULL,
  `profile1_id` INT NOT NULL,
  `profile2_id` INT NOT NULL,
  PRIMARY KEY (`contact_id`),
  CONSTRAINT `profile1_id`
    FOREIGN KEY (`profile1_id`)
    REFERENCES `profile` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `profile2_id`
    FOREIGN KEY (`profile2_id`)
    REFERENCES `profile` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisement` (
  `advert_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `payout` INT NULL,
  `location_lat` DOUBLE NULL,
  `location_long` DOUBLE NULL,
  `stage` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`advert_id`),
  CONSTRAINT `author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `profile` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisement_participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisement_participant` (
  `participation_id` INT NOT NULL,
  `participant_id` INT NOT NULL,
  `advert_id` INT NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`participation_id`),
  INDEX `participant_id` (`participant_id` ASC),
  INDEX `advert_id` (`advert_id` ASC),
  CONSTRAINT `participant_id`
    FOREIGN KEY (`participant_id`)
    REFERENCES `profile` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `advert_id`
    FOREIGN KEY (`advert_id`)
    REFERENCES `advertisement` (`advert_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisement_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advertisement_rating` (
  `rating_id` INT NOT NULL,
  `advert_id` INT NOT NULL,
  `author_id` INT NULL,
  `rating` INT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`rating_id`),
  CONSTRAINT `advert_id`
    FOREIGN KEY (`advert_id`)
    REFERENCES `advertisement` (`advert_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `profile` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `group_privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `group_privileges` (
  `privilege_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `level` TINYINT(4) NULL,
  PRIMARY KEY (`privilege_id`),
  INDEX `group_id` (`group_id` ASC),
  CONSTRAINT `privilege_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `group` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



